### ISSUE TITLE
Steam Core is busy

### ISSUE THREAD

**Issue by Cripix** [polvora/SteamCore#11]
Hi !

I use this [Plugin](https://github.com/yash1441/SteamInviter) but I have a recurring error.
So I try with this version of the [Plugin](https://github.com/yash1441/SteamInviter/blob/master/csgo/addons/sourcemod/scripting/SteamInviter.sp#L52-L56) 

And it gives me logs like that:

============================================================================

Logging in to keep login alive...

============================================================================

Obtaining RSA Key from steamcommunity.com/login/getrsakey...

And I have no more

Thanks !

**Comment by polvora** [comment]
Right now i'm rewriting the whole plugin so a lot of the problems tha that existed before should be gone with that release.

**Comment by Cripix** [comment]
Hello !

I have installed the latest version.

But the logs do not work.

Thanks

**Comment by polvora** [comment]
Did you check sourcemod/logs/steamcore_debug.log ??

**Comment by polvora** [comment]
Also how are using it?? i mean no plugin has been updated yet to use this library, if you are using it with the Steam Inviter of yash it won't work because that one is for an older version. Read the README file, because the install process has changed.

**Comment by polvora** [comment]
Also if you problem persists, open a new issue :)

**Comment by yash1441** [comment]
I have already updated it before this happened though.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Cripix** [comment]
I would like to see the logs but no log are created
And I have to configure everything and following the README.
