### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rsgua** [polvora/SteamCore#15]
Group invite request failed (1). Status Code: 500
L 10/08/2017 - 13:12:25: [steam/steamcore.smx] 
Preparing request to: 
http://steamcommunity.com/actions/GroupInvite...
L 10/08/2017 - 13:12:25: [steam/steamcore.smx] 
Invitee community ID: 
STEAM_ID_STOP_IGNORING_RETVALS
L 10/08/2017 - 13:12:25: [steam/steamcore.smx] 
Group community ID: 
103582791435260626
L 10/08/2017 - 13:12:25: [steam/steamcore.smx] 
Verifying login...
L 10/08/2017 - 13:12:25: [steam/steamcore.smx] 
Logged in, executing task....
L 10/08/2017 - 13:12:25: [steam/steamcore.smx] 
Group invite request failed (1). Status Code: 500

**Comment by polvora** [comment]
What plugin are you using to send the invites ? 
`Invitee community ID:
STEAM_ID_STOP_IGNORING_RETVALS`
I means the plugin generating the requests is not getting the Steam ID correctly.
