### ISSUE TITLE
Help with invites

### ISSUE THREAD

**Issue by Czar-VG** [polvora/SteamCore#4]
The group invite has been sent.
```Response body (160):
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><results><![CDATA[OK]]></results><groupId><![CDATA[103582791439566221]]></groupId></response>co�
```
But the invite never shows up. Any help would be great!

**Comment by polvora** [comment]
Weird, the message states the invite was sent (CDATA[OK]).
Does this happens with all the invited players? or just with one player? 
The account creating the invite has the rights to do so? (is not a limited account and has permission in the group)
Did it work in the past? remember accounts have a limit of invites sent daily.

**Comment by polvora** [comment]
Also sometimes invites dont popup in the steam overlay and are only shown in the notification box, make sure thats not your case.

**Comment by Czar-VG** [comment]
It was sending invites just fine yesterday then it just stopped sending them. I logged in and it would let me invite people from the account just not through the plugin. I tested it on three different accounts (in the steamcore plugin) and same result.

**Comment by Czar-VG** [comment]
Ill disable it for another day and see if it starts working again

**Comment by polvora** [comment]
There is a chance Steam changed something in the method to send invites tomorrow ill have time to test it and fix it. Thanks for the fast reply.

**Comment by polvora** [comment]
The plugin is working without problems, maybe you reached the invitation limit in all 3 accounts you used.
