### ISSUE TITLE
Exception Reported: Invalid function id (FFFFFFFF)

### ISSUE THREAD

**Issue by yash1441** [polvora/SteamCore#8]
```
L 07/10/2017 - 14:52:21: [SM] Blaming: steamcore.smx
L 07/10/2017 - 14:52:21: [SM] Call stack trace:
L 07/10/2017 - 14:52:21: [SM]   [0] RemoveFromForward
L 07/10/2017 - 14:52:21: [SM]   [1] Line 298, steamcore.sp::tmrBusyCallback
L 07/10/2017 - 14:52:21: [SM] Exception reported: Invalid function id (FFFFFFFF)
L 07/10/2017 - 14:52:21: [SM] Blaming: steamcore.smx
L 07/10/2017 - 14:52:21: [SM] Call stack trace:
L 07/10/2017 - 14:52:21: [SM]   [0] RemoveFromForward
L 07/10/2017 - 14:52:21: [SM]   [1] Line 298, steamcore.sp::tmrBusyCallback
```

What can be the problem here?

**Comment by polvora** [comment]
Does this happens always? or is this a one time thing? Very weird error. Thanks for reporting it!

**Comment by yash1441** [comment]
I made a plugin based on your SteamCore for someone and he got this error.
The plugin is here - https://github.com/yash1441/SteamInviter

**Comment by yash1441** [comment]
Yeah, he's getting it everytime and player's aren't being invited.

**Comment by polvora** [comment]
I'll take a look on it when im back from vacations,  that will be in 1 week. I tried solving it with my phone and teamviewer but i'm not that good with touch screens :p

**Comment by yash1441** [comment]
Check 3rd argument of function-call, you throwing invalid function id (I think you throwing integer (-1) wherever)
P.S. 0xFFFFFFFF is -1 in signed int

I asked the meaning of the error and someone from AlliedMods said this. You may already know this though, anyways.

**Comment by yash1441** [comment]
Another user posted this.

I believe -1 is also the value of the INVALID_FUNCTION constant, which some of the other function related calls return (such as GetFunctionByName) if they can't find the function you're looking for.

**Comment by polvora** [comment]
I don't know how you got that error, it's supossed to be prevented, also i just compiled the plugin you linked and it sent the invitation.

Maybe you are using an old version of steamcore?
I noticed you are using ReplyToCommand with a client but the one making the call is the server, probably not relevant but i just had to mention it.

**Comment by yash1441** [comment]
That's weird. I'll ask my client to redownload everything and check. 
Also, fixed with PrintToServer. Thanks!

**Comment by polvora** [comment]
Found the bug! This library was written before the release of sourcemod 1.7 when passing function references to arrays or datapacks was allowed. For some reason when i compiled the code it didn't trigger any warnings or errors (and it should). Probably a compiler bug that went unnoticed to this day.

By the nature of the bug i'll have to rewrite the way the plugin manages a call while busy. Right now i'm adding more functionalities to the code, so it will take a few days to solve this issue.

**Comment by yash1441** [comment]
Ah, that's good then! Thanks for your time.

**Comment by polvora** [comment]
Check https://github.com/polvora/SteamCore/releases/tag/v1.8 !
