### ISSUE TITLE
Steam Will Update Group Invites.

### ISSUE THREAD

**Issue by yash1441** [polvora/SteamCore#9]
Since the next steam update will add the following, I was wondering if it is possible to add an add as friend feature in SteamCore. 

"To address this, you can now only be invited into a group by your friends. This still maintains the common uses of forming a closed group to hang out with your friends, or creating a restricted group for people of similar interests or achievements."

**Comment by polvora** [comment]
For anyone reading, this is the link where this info came:
http://steamcommunity.com/games/593110/announcements/detail/1446071197008661976

I think the better approach now is just wait until they make the changes, cause probably the method to send invites and friend requests will be changing.

I have the intention of adding friend requests and chat messages in the future, but if things are going to change i'd rather wait.

If in the future, steam updates in a way that sending invites to people is extremely complicated or their spam detection system is so aggresive that it makes impossible to automate sending invites i will just remove the invite module from the plugin. A lot of people have being using this plugin to spam invites, and for that reason, we are part of the problem that made Steam take that desition.

**Comment by polvora** [comment]
I just noticed the changes were already made. Right now i'm adding an AddFriend native.
